version: "3"
services:
    postgres:
        image: "imunizeme/postgres"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_DB=imunizeme
        ports:
            - "5432:5432"
        volumes:
            - "./data/postgres:/var/lib/postgresql/data"
    prest:
        build: ./prest
        links:
            - "postgres:postgres"
        depends_on:
            - postgres
        environment:
            - IMUNIZEME_PG_HOST=postgres
            - IMUNIZEME_PG_USER=postgres
            - IMUNIZEME_PG_DBNAME=imunizeme
            - IMUNIZEME_PG_PORT=5432
            - IMUNIZEME_JWT_KEY=51d7fe292d4883dd6e408542denver
            - IMUNIZEME_PREST_PORT=3000
            - IMUNIZEME_PREST_HOST=0.0.0.0
            - IMUNIZEME_PREST_MIGRATIONS=./migrations
            - IMUNIZEME_PREST_QUERIES=./queries
    auth:
        build: ./auth
        environment:
            - IMUNIZEME_PG_HOST=postgres
            - IMUNIZEME_PG_USER=postgres
            - IMUNIZEME_PG_DBNAME=imunizeme
            - IMUNIZEME_PG_PORT=5432
            - IMUNIZEME_AUTH_PORT=4000
            - IMUNIZEME_AUTH_HOST=0.0.0.0
            - IMUNIZEME_JWT_KEY=51d7fe292d4883dd6e408542denver
    caddy:
        image: ./frontend
        links:
            - "prest:prest"
            - "auth:auth"
        volumes:
          - "./Caddyfile:/etc/Caddyfile"
        ports:
            - "443:443"